---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "milvus-operator"
  labels:
    helm.sh/chart: milvus-operator-1.3.5
    app.kubernetes.io/name: milvus-operator
    app.kubernetes.io/instance: milvus-operator
    app.kubernetes.io/version: "1.3.5"
    app.kubernetes.io/managed-by: Helm
