---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-kind: metrics
    helm.sh/chart: milvus-operator-1.3.5
    app.kubernetes.io/name: milvus-operator
    app.kubernetes.io/instance: milvus-operator
    app.kubernetes.io/version: "1.3.5"
    app.kubernetes.io/managed-by: Helm
  name: 'milvus-operator-metrics-service'
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    app.kubernetes.io/name: milvus-operator
    app.kubernetes.io/instance: milvus-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: milvus-operator-1.3.5
    app.kubernetes.io/name: milvus-operator
    app.kubernetes.io/instance: milvus-operator
    app.kubernetes.io/version: "1.3.5"
    app.kubernetes.io/managed-by: Helm
  name: 'milvus-operator-webhook-service'
spec:
  ports:
  - port: 443
    targetPort: webhook-server
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: milvus-operator
    app.kubernetes.io/instance: milvus-operator
