---
# Converted from ClusterRoleBinding to RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'milvus-operator-manager-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'milvus-operator-manager-role'
subjects:
- kind: ServiceAccount
  name: "milvus-operator"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'milvus-operator-leader-election-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'milvus-operator-leader-election-role'
subjects:
- kind: ServiceAccount
  name: "milvus-operator"
